# Generated by Django 4.2.1 on 2024-05-16 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_receipt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Women',
            new_name='Receipt',
        ),
    ]
