# Generated by Django 4.2.1 on 2024-05-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_receipt', '0002_rename_women_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='store',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='subtotal',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='total',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
