# Generated by Django 4.2.1 on 2024-05-17 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_receipt', '0003_alter_receipt_address_alter_receipt_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='address',
            new_name='location',
        ),
    ]
